default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: login
  password: password1

development:
  <<: *default
  host: localhost
  database:  login_development

test:
  adapter: sqlite3
  encoding: unicode
  database: test
  pool: 5

production:
  <<: *default
  database: login_production
